import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import Layout from "../components/layout";
import Profile from "../components/profile";
import Game from "../components/game";

const Home: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <Profile />
          <Game />
        </main>
      </div>
    </Layout>
  );
};

export default Home;
